version: '3.8'
services:
  backend:
    build:
      context: ./backend
    networks:
      - web_net
    ports:
      - "5000:5000"
    # volumes:
    #   - ./files/uploaded:/backend/files/uploaded
  
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      REACT_APP_BACKEND_HOST: "http://34.70.52.172:5000/api"
  
networks:
  web_net:
      driver: bridge
