version: '3.8'
services:
  backend:
    build:
      context: ./backend
    networks:
      - web_net
    ports:
      - "5000:5000"
    depends_on:
      - db
      - redis
  
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
  
  db:
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    image: "postgres:latest"
    networks:
      - web_net
    ports: 
      - "5432:5432"

  redis:
    image: redis
  
  celery:
    build:
      context: ./backend/file_processing
    command: celery -A tasks worker -l info
    depends_on:
      - backend
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
  
networks:
  web_net:
      driver: bridge