version: '3.8'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - redis
  
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      REACT_APP_BACKEND_HOST: "http://localhost:5000/api"  # TODO: Cambiar por URL del backend (misma maquina? load balancer?)
